version: "2"
services:
  os:
    container_name: myos
    image: ubuntu
    ports:
     - 8080:22/tcp
    volumes:
      - myvolume:/home/
    entrypoint: /bin/bash
    stdin_open: true # docker run -i
    tty: true # docker run -t  

volumes:
  myvolume:


